<!--<form action="/index.php/<?php echo $block->getFormAction() ?>" method="post">
    <input name="firstname" type="text" placeholder="First Name" required>
    <input name="lastname" type="text" placeholder="Last Name" required>
    <input name="email" type="email" placeholder="Email" required>
    <input name="dob" type="date">
    <input type="submit" value="Save">
</form>-->


<form action="/index.php/<?php echo $block->getFormAction() ?>" class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-4": {"required":true}}}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="field-1"><span>First Name</span></label>
            <div class="control">
                <input name="firstname" id="field-1" title="" value=""  class="input-text letters-only" type="text" data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-2"><span>Last Name</span></label>
            <div class="control">
                <input name="lastname" id="field-2" title="Last Name" value="" class="input-text letters-only" type="text" required="true"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-3"><span>Email</span></label>
            <div class="control">
                <input name="email" id="field-3" title="Email" value="" type="email" class="input-text" data-validate='{"required":true, "validate-email": true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-4"><span>Subject</span></label>
            <div class="control">
                <input name="subjet" id="field-4" title="Subject" value="" type="text" class="input-text" data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-5"><span>Description</span></label>
            <div class="control">
                <textarea name="description" id="field-5" title="Description" value="" class="input-text" data-validate='{"required":true, "max-words":250}'></textarea>
            </div>
        </div>
        <div class="field name">
            <label class="label" for="field-5"><span>DOB</span></label>
            <div class="control">
                <input name="dob" id="field-5" title="DOB" value="" class="input-text" type="date"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>