<div class="product_review_header">
  <h1><?php echo $block->getProductTitle() ?> - Product Reviews </h1>
  <?php if($block->getCustomerId()){ ?>
    <a class="button_review_form" href="/review/page/form/id/<?php echo $block->getProductId() ?>">Add Product Review</a>
  <?php } else { ?>
    <a class="button_review_form" href="http://bhpclocal.in/index.php/customer/account/login/">Sign In to Add Review</a>
  <?php } ?>
</div>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Product Name</th>
      <th>Rating</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Review</th>
    </tr>
  </thead>
  <tbody>
    <?php $reviews = $block->getReviewsByProductId(); 
    $j=1;
    if($reviews){
    foreach($reviews as $review){?>
    <tr>
      <td><?php echo $j++; ?></td>
      <td><?php echo $block->getProductName(); ?></td>
      <td><?php for($i=1; $i<=$review['product_rating']; $i++){echo '⭐';} ?></td>
      <td><?php echo $review['name'] ?></td>
      <td><?php echo $review['email'] ?></td>
      <td><?php echo $review['phone'] ?></td>
      <td><?php echo $review['product_description'] ?></td>
    </tr>
    <?php $j++; } 
    } else {?>
      <tr>
        <td colspan="7">Reviews are not available.</td>
      </tr>
    <?php } ?>
  </tbody>
</table>